services:
  app:
    build:
      context: .
      dockerfile: bloodtrail/demo/Dockerfile
    container_name: bloodtrail-app
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
    name: web
